clientpage/urls.py
from django.urls import path
from clientpage.views import index,accueil,pannier,ajouter_pannier,supprimer_pannier,connexion,acheter,facturation
from django.conf.urls.static import static
from django.conf import settings
app_name='clientpage'
urlpatterns = [
    path('',index,name='index'),
    path('accueil',accueil,name='accueil'),
    path('pannier',pannier,name='pannier'),
    path('ajouter_pannier/<article_id>',ajouter_pannier,name='ajouter_pannier'),
    path('supprimer_pannier/<id_article>',supprimer_pannier,name='supprimer_pannier'),
    path('connexion/',connexion,name='connexion'),
    path('acheter/',acheter,name='acheter'),
    path('facturation/<file>',facturation,name='facturation'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

stock/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrateur/',include('gestion.urls')),
    path('',include('clientpage.urls')),
]

clientpage/models.py
from django.db import models
from gestion.models import Article
class Compte(models.Model):
    nom=models.CharField(max_length=20)
    mdp=models.CharField(max_length=10)
    photo=models.ImageField(blank=True)

class Pannier(models.Model):
    articleid=models.ForeignKey(Article,on_delete=models.CASCADE,default=None)
    quantite=models.IntegerField()
    compte=models.ForeignKey(Compte,on_delete=models.CASCADE,default=None)

clientpage/forms.py
from django import forms
from .models import Compte,Pannier
class InscriptionForm(forms.ModelForm):
    class Meta:
        model=Compte
        fields=['nom','mdp','photo']

class ConnexionForm(forms.ModelForm):
    class Meta:
        model=Compte
        fields=['nom','mdp',]

class AjouterPannierForm(forms.Form):
        quantite=forms.IntegerField()
       

clientpage/views.py
from tempfile import NamedTemporaryFile
from django.shortcuts import render
from gestion.models import Article
from .models import Pannier,Compte
from .forms import InscriptionForm,AjouterPannierForm,ConnexionForm
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponse
from django.http import FileResponse
from django.template.loader import render_to_string
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import pdfkit
def index(request):
    connexion=False
    if request.method=='POST':
        form=InscriptionForm(request.POST,request.FILES)
        if form.is_valid():
            article=form.save()
            request.session['compte_id']=article.id
            print('valide')
            print(request.session.get('compte_id'))
            return redirect(reverse('clientpage:accueil'),permanent=True)
    else:
        form=InscriptionForm()
    
    return render(request,'index2.html',locals())

def accueil(request):
    articles=Article.objects.all()
    return render(request,'accueil.html',locals())

def ajouter_pannier(request,article_id):
    article=Article.objects.all().get(pk=article_id)
    compte_id=request.session.get('compte_id')
    compte=Compte.objects.all().get(pk=compte_id)
    if request.method=='POST':
        form=AjouterPannierForm(request.POST)
       
        if form.is_valid():
            quantite=form.cleaned_data['quantite']
            nouveau=Pannier()
            nouveau.articleid=article
            nouveau.quantite=quantite
            nouveau.compte=compte
            nouveau.save()
            return redirect(reverse('clientpage:pannier'),permanent=True)
            
            

    else:
        form=AjouterPannierForm()
    return render(request,'ajouter-pannier.html',locals())

def connexion(request):
    connexion=True
    if request.method=='POST':
        form=ConnexionForm(request.POST)
        if form.is_valid():
            nom=form.nom
            mdp=form.mdp
            print(nom)
            compte=Compte.objects.all().get(nom=nom)
            print(compte)
            return redirect(reverse('clientpage:accueil'),permanent=True)
    else:
        form=ConnexionForm()
    return render(request,'index2.html',locals())
        
def supprimer_pannier(request,id_article):
    compte_id=request.session.get('compte_id')
    compte=Compte.objects.all().get(pk=compte_id)
    pannierclient=Pannier.objects.filter(compte=compte)
    item=pannierclient.get(pk=id_article)
    item.delete()
    return render(request,'pannier.html',locals())
    
def facture(request,itemid):    
    
    reponse=HttpResponse(content_type='application/pdf')
    reponse['Content-Disposition']='facture.pdf'
    p=canvas.Canvas(reponse,pagesize=letter)
    
    p.showPage()
    p.save()
    return reponse

def facturation(request,file):
    
   
    config=pdfkit.configuration(wkhtmltopdf=r'/usr/bin/wkhtmltopdf')
    html = str(file.content, 'utf-8')
    with NamedTemporaryFile(delete=False, suffix='.html') as temp_html:
            temp_html.write(html.encode('utf-8'))
    try:

        print(temp_html.name)
        pdf=pdfkit.from_file(temp_html.name,False,configuration=config)
        response=HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition']='attachment; filename="file_name.pdf"'
        print('yyyu')
        return response        
    except Exception as e:
        
        
        
        return HttpResponse(f'Erreur lors du tele chargement de la facture {e}')
        

    
        
def pannier(request):
    try:
        compte_id=request.session.get('compte_id')
        print(compte_id)
        compte=Compte.objects.all().get(pk=compte_id)
        pannierclient=Pannier.objects.filter(compte=compte)
    except Exception as e:
        print(e)
    return render(request,'pannier.html',locals())



def acheter(request):
    if request.method=='POST':
        download=request.POST.get('telecharger')

        print(download)
        ligne=request.POST.getlist('ligne')
        lignes=list(map(int,ligne))
        compte_id=request.session.get('compte_id')
        compte=Compte.objects.all().get(pk=compte_id)
        pannierclient=Pannier.objects.filter(compte=compte)
        ligne_selectionne=[]
        somme=0
        for ligne in lignes:
            
            l=pannierclient.get(pk=ligne)
            p=l.articleid.prix*l.quantite
            somme +=p
            print(l.articleid.nom)
            ligne_selectionne.append(l)
        if download is not None:
            return facturation(request,render(request,'facture.html',locals()))
       
        return render(request,'facture.html',locals())
    return redirect('clientpage:pannier')

clientpage/templates/accueil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Acceuil</title>

    <style>
        *{
            margin: 0;
        }
        
        body{
            width: 100vw;
            display: flex;
            justify-content: center;
            flex-direction: column;
            align-items: center;
            background: black;
            color: white;
            overflow-x: hidden;
            
        }
        .items{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px,1fr));
            row-gap: 50px;
            width: 70vw;
            
            
            justify-content: center;
            
            
        }
        .item{
            width: 300px;
            height:300px;

        }
        .bas{
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        a{
            text-decoration: none;
            color:white;
            font-family: 'Courier New', Courier, monospace;
            font-weight: bold;

        }
        .info{
            font-family: 'Courier New', Courier, monospace;
            font-size: 12px;
            text-overflow: ellipsis;
            
        }
        .ajouter_pannier{
            border: 1px solid white;
            padding: 10px 5px;
            color: black;
            background: white;
        }
        .nav{
            margin-top: 20px;
            display: flex;
            gap: 30px;
            transition: all 1s;
        }
        .nav a:hover{
            color: aquamarine;
        }
        .nav a div{
            height: 2px;
            width: 0%;
            background:#fff;
        }
        
        .nav a:hover div{
            
            width: 100%;
            
        }
    </style>

</head>
<body>
   

    {% block navigation %}
    <div class="nav">
     <a href="#">Produits <div></div> </a>
     <a href="{% url 'clientpage:pannier' %}">Pannier<div></div></a>
     <a href="#">Faq<div></div></a>
     </div>
    {% endblock navigation %}
      
    <div class="banniere">
        <h1>Bienvenu sur Mangathèque</h1>
    </div>
    <div class="items">


        {% for article in articles  %}
            <div class="item">
            <div class="img">
                <img src={{article.photo.name}}  alt={{article.nom}} class='item' >
            </div>

            <div class="bas">
                <div class="info">
                    <p> {{article.nom}} </p>
                    <p class="prix">{{article.prix}} fcfa </p>
                    <p>Quantite: {{article.quantite}} </p>
                    
                </div>
                <div class="button">
                    <a href="{% url 'clientpage:ajouter_pannier' article.id %}" class="ajouter_pannier">Ajouter au pannier</a>
                </div>
            </div>
            </div>
        {% endfor %}
        

    </div>


</body>
</html>

clientpage/templates/ajouter-pannier.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter au pannier</title>
    <style>
        body{
            background: black;
            font-family: 'Courier New', Courier, monospace;
            height: 100vh;
            width: 100vw;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: white;
        }
        input[type='submit']{
            background: white;
            padding: 10px 20px;
            font-family: 'Courier New', Courier, monospace;
            color: black;
            border: none;
            font-weight: bold;
            cursor: grab;
            width: 100%;
            transition: all .5s linear;
        }
        input[type='submit']:hover{
            background: aqua;
        }
        span{
            color: aqua;
        }
    </style>
</head>
<body>
    <div class="article">
        <img src={{article.photo.url}} alt='{{article.nom}}' width="500px"> <br>
        {{article.nom |capfirst }}
        <span>{{article.quantite}}Exemplaires </span>
    </div>
    <form method="post" width="500px">
    
        {% csrf_token %}
        {{form.as_p}}
    <input type="submit" value="Ajouter">
    </form>
    
</body>
</html>

clientpage/templates/facture.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Facture</title>
<style>
    body{
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
        background: black;
        color: white;
        flex-direction: column;
        font-family: 'Courier New', Courier, monospace;
    }
    table{
        border: 1px solid white;
    }
    td{
        padding: 15px;
    }
    .Download{
        width: 350px;
        text-decoration: none;
        color: black;
        font-family: 'Courier New', Courier, monospace;
        background: white;
        margin: 10px;
        padding: 15px;
        text-align: center;
        font-weight: bold;
    }
</style>

</head>
<body>
    <div class="facture">
        Facturation
    </div>
    <table>
        <thead>
            <td>
                article
            </td>
            <td>
                Quantite
            </td>
            <td>
                prix
            </td>
        </thead>
        <tbody>

            
            {% for ligne in ligne_selectionne %}
            <tr>
                <td>
                   {{ligne.articleid.nom}}
                </td>
                <td>
                   {{ligne.quantite}}
                </td>
                <td>
                    {{ligne.articleid.prix}} Fcfa
                </td>
            </tr>
            {% endfor %}
                


        </tbody>
        <tfoot>
            <tr>
               <td colspan="2">
                Total A payer
            </td>
            <td>
                {{somme}} Fcfa
            </td> 
            </tr>
            
          
        </tfoot>

    </table>
    

</body>
</html>

clientpage/templates/index2.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Achat</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <style>
        body{
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            font-family: 'Courier New', Courier, monospace;
            background: black;
        }
        .entete{
            width: 100%;
        }
        form{
            width: 500px;
            display: flex;
            flex-direction: column;
            align-items: center;
            background: white;
            padding-bottom: 30px;
        }
        input{
            padding: 5px;
        }
        .btn_inscrire{
            background:#687FDB;
            border: none;
            padding: 10px 30px;
            color: white;
            font-weight: bold;
            font-family: 'Courier New', Courier, monospace;
            box-shadow: 0px 0px 5px black;
            border-radius: 5px;
            cursor: grab;
        }
    </style>

</head>

<body>

    {% if connexion %}
    <form  method="post">
        {% load static %}
        <img src="{% static 'images/onepiece.jpg' %}" alt="onepiece" class="entete"/>

        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Se connecter" class="btn_inscrire">
    </form>

{% else %}
<form  method="post">
    {% load static %}
    <img src="{% static 'images/onepiece.jpg' %}" alt="onepiece" class="entete"/>

    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="S'inscrire" class="btn_inscrire">
    
</form>

    {% endif %}


   
</body>
</html>

clientpage/templates/pannier.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pannier</title>

    <style>

        *{
            margin: 0;
        }
       table{
        border: 1px solid black;
        padding: 10px;
       }
       body{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100vh;
        font-family: sans-serif;
        background: black;
        color: white;
       }
       td{
        border-right: 1px solid black;
        border-bottom: 1px solid black;
       }
       caption{
        position: relative;
        left:0;
       }
       a{
        text-decoration: none;
        color:white;
        font-family: 'Courier New', Courier, monospace;
        font-weight: bold;

    }
    a div{
        height: 2px;
        width: 0%;
        background:#fff;
    }
    a:hover div{
        
        width: 100%;
        
    }
    a:hover{
        color:aqua;
    }
    .btn{
        border: 1px solid white;
        padding: 10px;
    }
  
    td{
        border: 1px solid white;
        padding: 5px;
    }
    </style>
</head>
<body>
    
    <form  method="post" action="{% url 'clientpage:acheter' %}">
        {% csrf_token %}
        <table>
            <thead>
                <td>
                    Article
                </td>
                <td>
                    Prix unitaire
                </td>
                <td>
                    Quantite
                </td>
                <td>
                    Total a payer
                </td>
                
            </thead>
            <tbody>
                
                
                {% for item in pannierclient %}
                
                   <tr>
                    <td>
                       <input type="checkbox" name="ligne" id="{{item.id}}" value="{{item.id}}"> {{ item.articleid.nom}}
                    </td>
                    <td>
                        {{ item.articleid.prix}}
                    </td>
                    <td>
                        {{ item.quantite }}
                    </td>
                    <td>
                        {{ item.articleid.prix}} * {{ item.quantite }}
                    </td>
                    
                    <td>
                        <a href="{% url 'clientpage:supprimer_pannier' item.id %}">
                            Supprimer
            {% load static %}
            <img src="{% static 'images/svg/trash-solid.svg' %}" alt="poubelle" width="10px"/>
                            </a>
                        </td>
                    </tr>
        
                    {% empty %}
                    Aucun article dans le Pannier
                    {% endfor %}
                        
                        
        
                </tbody>
                <input type="checkbox" name="telecharger" id="telecharger" value="telecharger"> telecharger la facture <br>
        </table>
        
    <input type="submit" value="Acheter">    
    </form>
   
</body>
</html>